# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6068823d2488f67d218f4522fa50c7bdcd5fbd7585c82f0d6d8b0dd59310b5ab9398ba3c3152ea0a9adc4b1a99edebbdc5c026517a64eb935dcbd360fa92f60a

test:
  secret_key_base: 91146821105907052616486fe025be045df0b3f0c3faffd78c8f1fbdac91a63eea2e594065a950ad0d36cc81b3adc17835ad770d163824c6c76af652b568f684

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>